* muslinks: name directories and files according to Dudl::Naming * muslinks: create Archive Jobfiles * added --help to all perl executables * added dudl-doarchive * perlified dudl-do* tools, giving them Getopt for usage and pod for   manpages

diff --git a/dudl-docdimg b/dudl-docdimg
--- a/dudl-docdimg
+++ b/dudl-docdimg
@@ -1,32 +1,113 @@
-#!/bin/sh
+#! /usr/bin/perl -w
 
-# generate CD images for new "sl" units
+# $Id: dudl-docdimg,v 1.4 2006-01-27 13:06:19 bj Exp $
 
-: ${outdir:=.}
+use strict;
+use Getopt::Long;
+use Dudl::Config;
+use Dudl::Misc;
 
-do_cd () {
-	local src="$1"
+=pod
 
-	name="`basename "$src"`"
-	num="`echo ${name} | sed -e 's/^sl0*//'`"
+=head1 NAME
 
-	if echo "$num" | grep -q '^[0-9]\{1,\}$'; then : ; else
-		echo "invalid dir name: $name">&2
-		return 1
-	fi
+dudl-docdimg - generate CD images for storage units
 
-	iso="$outdir/$name.iso"
-	if [ -r "$iso" ]; then
-		echo "file exists: $iso" >&2
-		return 1
-	fi
-	echo "generating $iso ..."
-	mkisofs -q -J -r -V "_MP3_${num}_" -o "$iso" "$src"
+=head1 SYNOPSIS
+
+dudl-docdimg [<opts>] <dir> ...
+
+=head1 DESCRIPTION
+
+TODO man desc
+
+
+=head1 OPTIONS
+
+=over 4
+
+=item B<--out> <dir>
+
+where to place generated images. default=.
+
+=cut
+
+my $opt_out = ".";
+
+=pod
+
+=item B<--help>
+
+display short usage info.
+
+=cut
+
+my $wanthelp;
+my $needhelp;
+
+if( ! GetOptions(
+	"help!"		=> \$wanthelp,
+	"out=s"		=> \$opt_out,
+)){
+	$needhelp++;
 }
 
-for i in "$@"; do
-	do_cd "$i"
-done
+if( $#ARGV < 0 ){
+	print STDERR "missing input directories\n";
+	$needhelp++;
+}
 
-# TODO: GetOptions + usage or perlify
-# TODO: manpage
+foreach my $dir ( @ARGV ){
+	if( ! &unitsplit($dir) ){
+		print STDERR "invalid dir name: $dir\n";
+		$needhelp++;
+	}
+
+	unless( -d $dir ){
+		print STDERR "no such dir: $dir\n";
+		$needhelp++;
+	}
+}
+
+if( $wanthelp ){
+	print <<EOF;
+usage: $0 <opts> <dir> ...
+ generate CD images for storage units
+options:
+ --help                  this short usage information.
+EOF
+	exit 0;
+}
+
+if( $needhelp ){
+	print STDERR "use --help for usage info\n";
+	exit 1;
+}
+
+my $dudl = new Dudl::Config;
+
+foreach my $dir ( @ARGV ){
+	my( $col, $num ) = &unitsplit( $dir );
+
+	my $unit = sprintf "\%s%04d", $col, $num;
+	my $iso = "$opt_out/$unit.iso";
+
+	-r $iso && die "image already exists: $iso";
+	
+	print "generating $iso ...\n";
+	system( "mkisofs -q -J -r -V _MP3_${num}_ -o \"$iso\" \"$dir\"" )
+		and die "mkisofs failed: $!";
+}
+
+=pod
+
+=head1 SEE ALSO
+
+I<Dudl::Overview>
+
+=head1 AUTHOR
+
+Rainer Clasen
+
+=cut
+
diff --git a/dudl-doout b/dudl-doout
--- a/dudl-doout
+++ b/dudl-doout
@@ -1,66 +1,148 @@
-#!/bin/sh
+#! /usr/bin/perl -w
 
-# try to move dirs from 3ren to 4out using dudl-rename
-#  dudl-doout <genre> <dir1> ...
-#  dudl-doout   # automagically picks all from 3ren
+# $Id: dudl-doout,v 1.4 2006-01-27 13:06:19 bj Exp $
+
+use strict;
+use Getopt::Long;
+use Dudl::Config;
+use Dudl::Misc;
+
+=pod
+
+=head1 NAME
+
+dudl-doout - rename MP3s from 3ren and place them in 4out
+
+=head1 SYNOPSIS
+
+dudl-doout [<opts>] [<genre> <dir> ...]
+
+=head1 DESCRIPTION
+
+TODO man desc
 
 
-set -e
+=head1 OPTIONS
 
-rdir="/pub/fun/mp3/3ren"
-odir="/pub/fun/mp3/4out"
+=over 4
 
-do_genre() {
-	local genre="$1"
-	shift
+=item B<--help>
 
-	case "$genre" in
-	 COMEDY|DANCE|POP|ROCK|SAMPLER)
-		:
-		;;
-	 *)
-		echo "invalid genre: >$genre<"
-		exit 1
-		;;
-	esac
+display short usage info.
 
-	gdir="$odir/$genre"
-	[ -d "$gdir" ] || mkdir "$gdir"
+=cut
 
-	for i in "$@"; do
-		if [ "$i"x = "*/"x ]; then
-			break
-		fi
+my $wanthelp;
+my $needhelp;
 
-		if [ -d "$i" ]; then
-			sdir="$i"
-			ren="$sdir/ren"
-		else
-			ren="$i"
-			sdir="${i%/*}"
-		fi
-
-		dudl-rename --outdir="$gdir" $ren
-		echo "hit ^C on error, ENTER on success"
-		read
-		rm -rf "$sdir"
-	done
+if( ! GetOptions(
+	"help!"		=> \$wanthelp,
+)){
+	$needhelp++;
 }
 
-if [ $# -eq 0 ]; then
-	cd "$rdir"
-	for sdir in */; do
-		( 
-		cd "$sdir"
-		genre=${sdir%%/}
-		do_genre "$genre" */
-		) || exit 1
-	done
-else
-	genre="`echo "$1" | tr '[a-z]' '[A-Z]' `"
-	shift
+if( $wanthelp ){
+	print <<EOF;
+usage: $0 <opts> [<genre> <dir> ...]
+ rename MP3s from 3ren and place them in 4out
+options:
+ --help                  this short usage information.
+EOF
+	exit 0;
+}
 
-	do_genre "$genre" "$@"
-fi
-# TODO: GetOptions + usage or perlify
-# TODO: manpage
+if( $needhelp ){
+	print STDERR "use --help for usage info\n";
+	exit 1;
+}
+
+my $dudl = new Dudl::Config;
+
+my $rdir = $dudl->conf("workpath") . "/3ren";
+my $odir = $dudl->conf("workpath") . "/4out";
+
+if( $#ARGV < 0 ){
+	opendir(R, $rdir)
+		or die "opendir: $!";
+	while ( defined (my $gdir = readdir(R)) ){
+		&do_gdir( $gdir ) or exit 1;
+	}
+	closedir(R);
+
+} elsif( $#ARGV < 1 ){
+	print STDERR "missing directories\n";
+	exit 1;
+
+} else {
+	my $genre = shift;
+
+	foreach my $dir (@ARGV){
+		&do_dir( $genre, $dir )
+			or exit 1;
+	}
+}
+
+sub do_gdir {
+	my( $gdir ) = @_;
+
+	&checkgenre($gdir) or return 1;
+
+	opendir(G, "$rdir/$gdir" )
+		or die "opendir: $!";
+	while ( defined (my $dir = readdir(G)) ){
+		next if $dir =~ /^\./;
+		&do_dir( $gdir, "$rdir/$gdir/$dir" ) or return;
+	}
+	closedir(G);
+
+	return 1;
+}
+
+sub do_dir {
+	my( $garg, $arg ) = @_;
+
+	print $arg, "\n";
+
+	my $genre = &checkgenre($garg);
+	if( ! defined $genre ){
+		print STDERR "invalid genre: $garg\n";
+		return;
+	}
+	
+	my( $dir, $ren );
+	if( -d $arg ){
+		$dir = $arg;
+		$ren = "$dir/ren";
+	} elsif( $arg =~ /^(.+)\/([^\/]+)$/ ){
+		$dir = $1;
+		$ren = $arg;
+	} else {
+		print STDERR "no such directory: $arg\n";
+		return;
+	}
+
+	-d "$odir/$genre" or mkdir 0777, "$odir/$genre";
+	system("dudl-rename --outdir \"$odir/$genre\" \"$ren\"") == 0
+		or die "rename failed: $!";
+	
+	print "hit ENTER to continue";
+	$_ = <>;
+	exit if /^q$/i;
+
+	system("rm -rf \"$dir\"") == 0
+		or die "rm failed: $!";
+}
+
+
+=pod
+
+=head1 SEE ALSO
+
+I<Dudl::Overview>
+
+=head1 AUTHOR
+
+Rainer Clasen
+
+=cut
+
diff --git a/dudl-doren b/dudl-doren
--- a/dudl-doren
+++ b/dudl-doren
@@ -1,54 +1,133 @@
-#!/bin/sh
+#! /usr/bin/perl -w
 
-# move dirs from 2test 
-# - to 4ren using dudl-rename if "ren" file works flawlessly
-# - to 3ren otherwise
+# $Id: dudl-doren,v 1.5 2006-01-27 13:06:19 bj Exp $
 
-# dudl-doren <genre> <dir1> [...]
+use strict;
+use Getopt::Long;
+use Dudl::Config;
+use Dudl::Misc;
 
-set -e
-rdir="/pub/fun/mp3/3ren"
-odir="/pub/fun/mp3/4out"
+=pod
 
-genre="`echo "$1" | tr '[a-z]' '[A-Z]' `"
-shift
+=head1 NAME
 
-case "$genre" in
- COMEDY|DANCE|POP|ROCK|SAMPLER)
-	:
-	;;
- *)
- 	echo "invalid genre: >$genre<"
-	exit 1
-	;;
-esac
+dudl-doren - move dirs from 2test to 3ren or possibly 4out
 
+=head1 SYNOPSIS
 
-for i in "$@"; do
-	if [ -d "$i" ]; then
-		sdir="$i"
-		ren="$sdir/ren"
-	else
-		ren="$i"
-		sdir="${i%/*}"
-	fi
+dudl-doren [<opts>] <genre> <dir> ...
 
-	echo "processing $ren"
-	if dudl-rename --test "$ren" > /dev/null 2>&1 ; then
-		gdir="$odir/$genre"
-		[ -d "$gdir" ] || mkdir "$gdir"
+=head1 DESCRIPTION
 
-		dudl-rename --outdir="$gdir" "$ren"
-		echo "hit ^C on error, ENTER on success"
-		read
-		rm -rf "$sdir"
-	else
-		gdir="$rdir/$genre"
-		[ -d "$gdir" ] || mkdir "$gdir"
+TODO: man desc
+move dirs from 2test 
 
-		# TODO: avoid overwriting itself
-		mv "$sdir" "$gdir/"
-	fi
-done
-# TODO: GetOptions + usage or perlify
-# TODO: manpage
+=over 2
+
+=item *
+
+to 4ren using dudl-rename if "ren" file works flawlessly
+
+=item *
+
+to 3ren otherwise
+
+=back
+
+=head1 OPTIONS
+
+=over 4
+
+=item B<--help>
+
+display short usage info.
+
+=cut
+
+my $wanthelp;
+my $needhelp;
+
+if( ! GetOptions(
+	"help!"		=> \$wanthelp,
+)){
+	$needhelp++;
+}
+
+my $genre = &checkgenre( shift );
+if( ! defined $genre ){
+	print STDERR "invalid/missing genre\n";
+	$needhelp++;
+}
+
+if( $#ARGV < 0 ){
+	print STDERR "missing directory\n";
+	$needhelp++;
+}
+
+if( $wanthelp ){
+	print <<EOF;
+usage: $0 <opts> <genre> <dir> ...
+ move dirs from 2test to 3ren or possibly 4out
+options:
+ --help                  this short usage information.
+EOF
+	exit 0;
+}
+
+if( $needhelp ){
+	print STDERR "use --help for usage info\n";
+	exit 1;
+}
+
+my $dudl = new Dudl::Config;
+my $rdir = $dudl->conf("workpath") . "/3ren";
+my $odir = $dudl->conf("workpath") . "/4out";
+
+for my $arg ( @ARGV ){
+	my( $dir, $ren );
+	if( -d $arg ){
+		$dir = $arg;
+		$ren = "$dir/ren";
+	} elsif( $arg =~ /^(.+)\/([^\/]+)$/ ){
+		$dir = $1;
+		$ren = $arg;
+	} else {
+		print STDERR "no such directory: $arg\n";
+		return;
+	}
+
+	if( 0 != system("dudl-rename --test \"$ren\"" )){
+		system("dudl-rename --outdir \"$odir/$genre\" \"$ren\"") == 0
+			or die "rename failed: $!";
+	
+		print "hit ENTER to continue";
+		$_ = <>;
+		exit if /^q$/i;
+
+		system("rm -rf \"$dir\"") == 0
+			or die "rm failed: $!";
+	
+	} else {
+		-d "$rdir/$genre" or mkdir 0777, "$rdir/$genre";
+		if( &samedir( "$rdir/$genre", &parentdir($dir)) ){
+			print STDERR "directory is alredy in 3ren: $dir\n";
+			next;
+		}
+
+		system("mv \"$dir\" \"$rdir/$genre\"") == 0
+			or die "mv failed: $!";
+	}
+}
+
+=pod
+
+=head1 SEE ALSO
+
+I<Dudl::Overview>
+
+=head1 AUTHOR
+
+Rainer Clasen
+
+=cut
+
diff --git a/dudl-dotest b/dudl-dotest
--- a/dudl-dotest
+++ b/dudl-dotest
@@ -1,46 +1,132 @@
-#!/bin/sh
+#! /usr/bin/perl -w
 
-# move new album to test directory normalizing all filenames
-#  dudl-dotest <dir> ...
-#  prefix=metallica- dudl-dotest master.of.puppets
+# $Id: dudl-dotest,v 1.5 2006-01-27 13:06:19 bj Exp $
 
-set -e
+use strict;
+use Getopt::Long;
+use Dudl::Config;
+use Dudl::Misc;
 
-: ${prefix:=}
-tstdir=/pub/fun/mp3/2test
+=pod
 
-do_dir () {
-	local src="$1"
-	if [ -d "$src" ]; then : ; else
-		echo "skipping non-dir: $src" >&2
-		return 1
-	fi
+=head1 NAME
 
-	# TODO: strip trailing 'the|die|...' from directory names
-	dst="$(dudl-fname "`basename "$src"`")"
-	mv "$src" "$tstdir/$prefix$dst"
-	(
-		cd "$tstdir/$prefix$dst" 
-		dudl-fclean *
-		[ -r ren ] \
-			|| find . -type f -iname \*.mp3 \
-			| sort \
-			| ( 
-				printf "TODO: edit\n# TODO: year\n"
-				dudl-rengen -
-			)  > ren 2>/dev/null 
-	)
+dudl-dotest - add MP3 directory to testing workspace
+
+=head1 SYNOPSIS
+
+dudl-dotest [<opts>] <dir> ...
+
+=head1 DESCRIPTION
+
+TODO: man desc
+
+
+=head1 OPTIONS
+
+=over 4
+
+=item B<--prefix>=<string>
+
+prefix new directory names with speciefied string.
+
+=cut
+
+my $opt_prefix = "";
+
+=item B<--help>
+
+display short usage info.
+
+=cut
+
+my $wanthelp;
+my $needhelp;
+
+if( ! GetOptions(
+	"help!"		=> \$wanthelp,
+	"prefix=s"	=> \$opt_prefix,
+)){
+	$needhelp++;
 }
 
-if [ $# -gt 0 ]; then
-	for src in "$@"; do
-		do_dir "$src"
-	done
-else
-	while read src; do
-		do_dir "$src"
-	done
-fi
+if( $#ARGV < 0 ){
+	print STDERR "missing directory\n";
+	$needhelp++;
+}
 
-# TODO: GetOptions + usage or perlify
-# TODO: manpage
+
+if( $wanthelp ){
+	print <<EOF;
+usage: $0 <opts> <dir> ...
+ add MP3 directory to testing workspace
+options:
+ --help                  this short usage information.
+ --prefix <string>       prefix new directory names with speciefied string
+EOF
+	exit 0;
+}
+
+if( $needhelp ){
+	print STDERR "use --help for usage info\n";
+	exit 1;
+}
+
+my $dudl = new Dudl::Config;
+my $nam = $dudl->naming;
+my $tdir = $dudl->conf("workpath"). "/2test";
+
+if( $opt_prefix && $opt_prefix !~ /-$/ ){
+	$opt_prefix .= "-";
+}
+
+foreach my $src ( @ARGV ){
+	unless( -d $src ){
+		print STDERR "skipping non-dir: $src\n";
+		next;
+	}
+
+	if( &samedir( &parentdir( $src ), $tdir )){
+		print STDERR "already in testing workspace: $src\n";
+		next;
+	}
+
+	$src =~ /([^\/]+)\/*$/;
+	my $dst = $tdir . "/". $nam->fnormalize( $opt_prefix.$1 );
+	system( "mv \"$src\" \"$dst\"" ) == 0
+		or die "mv failed: $1";
+
+	-e "$dst/ren" || &mkren( $dst )
+		or die "creating jobfile failed";
+}
+
+sub mkren {
+	my( $dst ) = @_;
+
+	# TODO: re-user M3U playlists
+
+	# TODO: perlify jobfile generation
+	system( "cd \"$dst\" && find . -type f -iname \\*.mp3 | sort | ( printf \"TODO: edit\\n# TODO: year\\n\"; dudl-rengen - ) > ren 2>/dev/null") == 0
+		or return;
+
+	return 1;
+}
+
+=pod
+
+=head1 EXAMPLES
+
+dudl-dotest --prefix metallica- master.of.puppets/
+
+=head1 SEE ALSO
+
+I<Dudl::Overview>
+
+=head1 AUTHOR
+
+Rainer Clasen
+
+=cut
+
+
+
